name: NekoBorder
version: '${version}'
main: org.encinet.nekoborder.NekoBorder
api-version: '1.20'
authors: [ Noctiro ]
description: Make Border Better
website: https://github.com/encinet
commands:
  nekoborder:
    aliases:
      - border
      - nborder
    description: Reload
permissions:
  nekoborder.commands:
    description: Use Command
    default: op
